# +----------------------------------------------------------------------------
# | Copyright (c) 2022 Pivotal Commware
# | All rights reserved.
# | 
# | job-build.yml
# | reusable Azure pipeline build steps
# +----------------------------------------------------------------------------
jobs:
  - job: Api
    steps:
    - checkout: self
    - task: UsePythonVersion@0
      displayName: "Installing Python 3.9"
      inputs:
        versionSpec: '3.9'
        architecture: 'x64'
    - script: |
        az --version
        curl -sL https://packages.microsoft.com/keys/microsoft.asc |
        gpg --dearmor |
        sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
        sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        az upgrade --yes
        az --version
      displayName: Upgrade Azure CLI
    - bash: './bin/api-build.sh'
      name: Build
    - publish: '$(Build.apiArtifact)'
      artifact: ApiPackage
      displayName: Publish Package